name: Build iOS app

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and unzip Godot iOS template
        run: |
          wget -O ios_template.zip "https://dl.dropboxusercontent.com/scl/fi/qg4ofedro2xsr0wtyz6sd/ios.zip?rlkey=avw6jlbtcztrenumz9wb2nwd9&dl=1"
          unzip ios_template.zip -d godot_ios

      - name: Build archive and ipa from godot_ios
        run: |
          cd godot_ios
          xcodebuild archive -project godot_ios.xcodeproj -scheme 'godot_ios' -archivePath godot_ios.xcarchive -configuration Release CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          mkdir Payload
          mv godot_ios.xcarchive/Products/Applications/godot_ios.app Payload/godot_ios.app
          zip -r "godot_ios.ipa" Payload
          mv godot_ios.ipa ${{ runner.temp }}/godot_ios.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot_ios
          path: ${{ runner.temp }}/godot_ios.ipa
          retention-days: 3
